# Meta
title:            Guardian Next
tagline:          ''
baseurl:          http://next.theguardian.com
author:
  name:           'The Guardian'
  url:            https://twitter.com/guardian

# Dependencies
markdown:         redcarpet
redcarpet:
  extensions:     [smart]
pygments:         true

# Setup
permalink:        /updates/:title/
paginate:         10
paginate_path:    "/updates/page:num"

# Navigation
navigation:
- text: Home
  mobiletext: Home
  url: /
- text: Blog
  mobiletext: Blog
  url: /updates/
- text: Feedback
  mobiletext: Feedback
  url: /feedback/

# Authors
authors:
  paulrobertlloyd:
    display_name: Paul Lloyd
    gravatar: 0bce06bd06ee7a2c4f5500f25dcf7f18
    twitter: paulrobertlloyd
    github: paulrobertlloyd
  cantlin:
    display_name: Cantlin Ashrowan
    gravatar: aff34dfa0f47d7072108a836a06bb5fd
    twitter: cantlin
    github: cantlin
  kungpochicken:
    display_name: Chris Mulholland
    gravatar: 
    twitter: kungpochicken
    github: kungpochicken
  jfitzell:
    display_name: Julian Fitzell
    gravatar: 
    twitter: jfitzell
    github: 
  kaelig:
    display_name: Kaelig Deloumeau-Prigent
    gravatar: f7e7b837bd06d6193f4ac70f17e6f44b
    twitter: kaelig
    github: kaelig
  phamann:
    display_name: Patrick Hamann
    gravatar: 276c149f793de9af4e98991ed52ff874
    twitter: phamann
    github: phamann
